name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build fastfreeze.tar.xz
      run: scripts/build.sh
    - name: Run tests
      run: scripts/run_tests.sh
    - name: Upload fastfreeze.tar.xz
      uses: actions/upload-artifact@v2
      with:
        name: fastfreeze.tar.xz
        path: |
          fastfreeze.tar.xz
